# .github/workflows/main.yml

# 工作流名称
name: Update Cloudflare Preferred IPs

on:
  # 允许手动触发此工作流
  workflow_dispatch:

  # 设置定时任务
  schedule:
    # 使用 Cron 表达式，表示每6小时运行一次
    # 具体时间是 UTC 时间的 0点, 6点, 12点, 18点
    - cron: '0 * * * *'

jobs:
  update-dns:
    # 使用最新的 Ubuntu 运行环境
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 指定 Python 版本

      # 第三步：安装依赖库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 第四步：运行更新脚本
      - name: Run IP Update Script
        env:
          # 将 GitHub Secrets 传递给 Python 脚本作为环境变量
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_DOMAIN_NAME: ${{ secrets.CF_DOMAIN_NAME }}
        run: python update_ips.py
